const a= "racheli"
let b = "ccc"
try{console.log(a+b)}
catch{ console.log("error")}
console.log(a);
